# Generated by Django 6.1.1 on 2026-09-26 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subject', models.TextField(blank=True, default='(No Subject)')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('recipients_to', models.JSONField(default=list, help_text='List of To recipients')),
                ('recipients_cc', models.JSONField(default=list, help_text='List of Cc recipients')),
                ('recipients_bcc', models.JSONField(default=list, help_text='List of Bcc recipients')),
                ('sent_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('folder_path', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('body_plain', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('importance', models.IntegerField(default=1, help_text='0: Low, 1: Normal, 2: High')),
                ('conversation_topic', models.CharField(blank=True, default='', max_length=512)),
                ('has_attachments', models.BooleanField(db_index=True, default=False)),
                ('attachment_count', models.IntegerField(default=0)),
                ('matched_keywords', models.JSONField(default=list)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('risk_level', models.CharField(default='Low', max_length=16)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['-sent_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailboxInvestigation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_ref', models.CharField(db_index=True, help_text='Audit Reference / Case Number', max_length=64)),
                ('audit_name', models.CharField(help_text='Investigation / Audit Title', max_length=255)),
                ('auditee_name', models.CharField(help_text='Target Auditee / Custodian Name', max_length=255)),
                ('auditee_email', models.EmailField(help_text='Auditee Primary Corporate Email', max_length=255)),
                ('auditee_department', models.CharField(blank=True, default='', help_text='Department / Business Unit', max_length=128)),
                ('auditee_designation', models.CharField(blank=True, default='', help_text='Auditee Official Title', max_length=128)),
                ('pst_file_name', models.CharField(max_length=255)),
                ('pst_file_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, default='', help_text='Chain of Custody Hash', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('UPLOADING', 'Uploading PST File'), ('PROCESSING', 'Extracting & Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('current_folder', models.CharField(blank=True, default='', max_length=255)),
                ('total_messages_estimated', models.IntegerField(default=0)),
                ('processed_messages_count', models.IntegerField(default=0)),
                ('attachment_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mailbox Investigation',
                'verbose_name_plural': 'Mailbox Investigations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='application/octet-stream', max_length=128)),
                ('file_extension', models.CharField(blank=True, default='', max_length=32)),
                ('sha256_hash', models.CharField(db_index=True, help_text='Evidence Hash', max_length=64)),
                ('storage_path', models.CharField(blank=True, default='', help_text='Extracted file path', max_length=512)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='q_mail.emailmessage')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ['filename'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='q_mail.mailboxinvestigation'),
        ),
        migrations.CreateModel(
            name='EmailParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('sent_count', models.IntegerField(default=0)),
                ('received_count', models.IntegerField(default=0)),
                ('first_interaction', models.DateTimeField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('is_external_domain', models.BooleanField(default=False)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='q_mail.mailboxinvestigation')),
            ],
            options={
                'verbose_name': 'Email Participant',
                'verbose_name_plural': 'Email Participants',
                'ordering': ['-sent_count', '-received_count'],
                'unique_together': {('mailbox', 'email_address')},
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['mailbox', '-sent_date'], name='q_mail_emai_mailbox_72d0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['mailbox', 'risk_score'], name='q_mail_emai_mailbox_90a6ee_idx'),
        ),
    ]
