# Generated by Django 6.1.1 on 2026-09-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailmessage',
            name='q_mail_emai_mailbox_90a6ee_idx',
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['mailbox', 'folder_path', '-sent_date'], name='q_mail_emai_mailbox_f131df_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['mailbox', 'sender_email', '-sent_date'], name='q_mail_emai_mailbox_c84fae_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['mailbox', 'has_attachments', '-sent_date'], name='q_mail_emai_mailbox_143e86_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['mailbox', 'risk_score', '-sent_date'], name='q_mail_emai_mailbox_8b5686_idx'),
        ),
    ]
