# Generated by Django 6.1.1 on 2026-10-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profiledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationprofile',
            name='category',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('VENDOR', 'Vendor'), ('RELATIVE_OF_EMPLOYEE', 'Relative of Employee'), ('OTHER', 'Other / Third Party')], db_index=True, default='EMPLOYEE', help_text='Target profile category / affiliation', max_length=32),
        ),
        migrations.AddField(
            model_name='investigationprofile',
            name='related_employee',
            field=models.CharField(blank=True, default='', help_text='Related employee name, ID, or relationship details', max_length=255),
        ),
    ]
