import json
import plotly.express as px
from django.shortcuts import render

def component_test_view(request):
    """
    Component Sandbox View for testing Plotly and Tabulator Cotton tags.
    """
    fig = px.bar(
        x=["Acme Logistics", "Krishna Ent", "Atul Billing", "Shadow Corp", "Nexus Trade"], 
        y=[240000, 185000, 42000, 520000, 310000],
        labels={"x": "Vendor / Counterparty", "y": "Transfer Amount (INR)"},
        color_discrete_sequence=["#f59e0b"] # Amber-500
    )
    fig.update_layout(
        template="plotly_dark",
        margin=dict(l=20, r=20, t=30, b=20),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(family="Inter, sans-serif", color="#a1a1aa"),
        xaxis=dict(gridcolor="#27272a", linecolor="#27272a"),
        yaxis=dict(gridcolor="#27272a", linecolor="#27272a"),
    )
    chart_html = fig.to_html(full_html=False, include_plotlyjs=False)

    table_columns = [
        {"title": "Date", "field": "date", "width": 120},
        {"title": "Counterparty", "field": "party"},
        {"title": "Direction", "field": "direction", "width": 100},
        {"title": "Amount", "field": "amount", "formatter": "money", "formatterParams": {"symbol": "INR ", "precision": 2}},
        {"title": "Status", "field": "status", "width": 130},
    ]
    
    table_data = [
        {"id": 1, "date": "2026-03-12", "party": "Acme Logistics", "direction": "IN", "amount": 240000, "status": "Cleared"},
        {"id": 2, "date": "2026-03-19", "party": "Atul Enterprises", "direction": "OUT", "amount": -185000, "status": "Flagged"},
        {"id": 3, "date": "2026-03-26", "party": "Krishna Contractor", "direction": "OUT", "amount": -320500, "status": "Under Review"},
        {"id": 4, "date": "2026-03-28", "party": "Shadow Holdings LLC", "direction": "OUT", "amount": -520000, "status": "Escalated"},
        {"id": 5, "date": "2026-03-30", "party": "Apex Global Traders", "direction": "IN", "amount": 1250000, "status": "Cleared"},
    ]

    return render(request, "demo/test_dashboard.html", {
        "chart_html": chart_html,
        "table_columns": json.dumps(table_columns),
        "table_data": json.dumps(table_data),
    })


def tabulator_demo_view(request):
    """
    Comprehensive forensic transaction analysis demo showcasing Tabulator.js.
    """
    forensic_records = [
        {
            "id": 101,
            "ref_no": "TXN-98412",
            "date": "2026-03-01 09:23",
            "party": "Shadow Apex Holdings Ltd",
            "account_no": "HDFC-****-8841",
            "category": "Shell Entity Wire",
            "direction": "OUT",
            "amount": -2450000,
            "risk_score": 94,
            "risk_level": "High",
            "status": "Escalated",
            "flag_reason": "Layered offshore transfer with zero trade history",
        },
        {
            "id": 102,
            "ref_no": "TXN-98413",
            "date": "2026-03-02 11:45",
            "party": "Acme Logistics Infrastructure",
            "account_no": "ICIC-****-2311",
            "category": "Vendor Payment",
            "direction": "IN",
            "amount": 1820000,
            "risk_score": 18,
            "risk_level": "Low",
            "status": "Cleared",
            "flag_reason": "Standard verified vendor payout",
        },
        {
            "id": 103,
            "ref_no": "TXN-98414",
            "date": "2026-03-03 14:10",
            "party": "Nexus Global Trading FZE",
            "account_no": "HSBC-****-7890",
            "category": "International Remittance",
            "direction": "OUT",
            "amount": -4300000,
            "risk_score": 88,
            "risk_level": "High",
            "status": "Flagged",
            "flag_reason": "High-risk tax haven destination",
        },
        {
            "id": 104,
            "ref_no": "TXN-98415",
            "date": "2026-03-04 16:30",
            "party": "Krishna Heavy Industries",
            "account_no": "SBI-****-4123",
            "category": "Director Loan Repayment",
            "direction": "IN",
            "amount": 750000,
            "risk_score": 45,
            "risk_level": "Medium",
            "status": "Under Review",
            "flag_reason": "Unusual director loan payback timeline",
        },
        {
            "id": 105,
            "ref_no": "TXN-98416",
            "date": "2026-03-05 10:05",
            "party": "BlueSky Export & Clearing LLP",
            "account_no": "AXIS-****-9012",
            "category": "Over-invoicing Scheme",
            "direction": "OUT",
            "amount": -1650000,
            "risk_score": 79,
            "risk_level": "High",
            "status": "Flagged",
            "flag_reason": "Invoice rate 320% higher than market median",
        },
        {
            "id": 106,
            "ref_no": "TXN-98417",
            "date": "2026-03-06 18:22",
            "party": "Standard Operations Corp",
            "account_no": "KOTK-****-3344",
            "category": "Payroll Batch",
            "direction": "OUT",
            "amount": -890000,
            "risk_score": 12,
            "risk_level": "Low",
            "status": "Cleared",
            "flag_reason": "Routine verified employee payroll",
        },
        {
            "id": 107,
            "ref_no": "TXN-98418",
            "date": "2026-03-07 12:15",
            "party": "Benami Proxy Enterprise",
            "account_no": "CANR-****-1002",
            "category": "Cash Smurfing / Layering",
            "direction": "IN",
            "amount": 490000,
            "risk_score": 92,
            "risk_level": "High",
            "status": "Escalated",
            "flag_reason": "10 consecutive cash deposits just below statutory reporting threshold",
        },
        {
            "id": 108,
            "ref_no": "TXN-98419",
            "date": "2026-03-08 09:50",
            "party": "Zenith Advisory Services",
            "account_no": "HDFC-****-6541",
            "category": "Consulting Retainer",
            "direction": "OUT",
            "amount": -350000,
            "risk_score": 38,
            "risk_level": "Medium",
            "status": "Under Review",
            "flag_reason": "Vague deliverables in management consultancy invoice",
        },
        {
            "id": 109,
            "ref_no": "TXN-98420",
            "date": "2026-03-09 15:40",
            "party": "Prime Steel Suppliers",
            "account_no": "PNB-****-8765",
            "category": "Raw Material Purchase",
            "direction": "IN",
            "amount": 3100000,
            "risk_score": 15,
            "risk_level": "Low",
            "status": "Cleared",
            "flag_reason": "Verified GST e-way bill matching physical delivery",
        },
        {
            "id": 110,
            "ref_no": "TXN-98421",
            "date": "2026-03-10 17:05",
            "party": "Vortex FinTech Shell Corp",
            "account_no": "IDFC-****-4598",
            "category": "Hawala Layering",
            "direction": "OUT",
            "amount": -5800000,
            "risk_score": 98,
            "risk_level": "High",
            "status": "Escalated",
            "flag_reason": "Rapid pass-through: Funds exited within 4 minutes of arrival",
        },
        {
            "id": 111,
            "ref_no": "TXN-98422",
            "date": "2026-03-11 11:20",
            "party": "Global Logistics Freight Co",
            "account_no": "ICIC-****-9128",
            "category": "Freight Forwarding",
            "direction": "OUT",
            "amount": -420000,
            "risk_score": 22,
            "risk_level": "Low",
            "status": "Cleared",
            "flag_reason": "Standard custom clearing fee",
        },
        {
            "id": 112,
            "ref_no": "TXN-98423",
            "date": "2026-03-12 13:45",
            "party": "Phoenix Realty Ventures",
            "account_no": "YESB-****-1190",
            "category": "Circular Real Estate Advances",
            "direction": "IN",
            "amount": 6200000,
            "risk_score": 85,
            "risk_level": "High",
            "status": "Flagged",
            "flag_reason": "Circular routing back to originator via 3rd party escrow",
        },
        {
            "id": 113,
            "ref_no": "TXN-98424",
            "date": "2026-03-13 16:10",
            "party": "Apex Hardware Corp",
            "account_no": "HDFC-****-5561",
            "category": "Capital Equipment",
            "direction": "OUT",
            "amount": -1150000,
            "risk_score": 28,
            "risk_level": "Low",
            "status": "Cleared",
            "flag_reason": "Machinery procurement backed by OEM warranty",
        },
        {
            "id": 114,
            "ref_no": "TXN-98425",
            "date": "2026-03-14 10:15",
            "party": "Kavita Trading Syndicate",
            "account_no": "SBI-****-3301",
            "category": "Bogus Billing Network",
            "direction": "OUT",
            "amount": -2100000,
            "risk_score": 89,
            "risk_level": "High",
            "status": "Escalated",
            "flag_reason": "Counterparty GSTIN cancelled for fraudulent ITC claims",
        },
        {
            "id": 115,
            "ref_no": "TXN-98426",
            "date": "2026-03-15 14:55",
            "party": "Delta Software Systems",
            "account_no": "CITI-****-6623",
            "category": "IT License Subscriptions",
            "direction": "OUT",
            "amount": -650000,
            "risk_score": 30,
            "risk_level": "Low",
            "status": "Cleared",
            "flag_reason": "Quarterly enterprise SaaS billing",
        },
    ]

    total_inflow = sum(r["amount"] for r in forensic_records if r["amount"] > 0)
    total_outflow = sum(r["amount"] for r in forensic_records if r["amount"] < 0)
    high_risk_count = sum(1 for r in forensic_records if r["risk_level"] == "High")
    escalated_count = sum(1 for r in forensic_records if r["status"] == "Escalated")

    return render(request, "demo/tabulator_demo.html", {
        "forensic_records_json": json.dumps(forensic_records),
        "total_records": len(forensic_records),
        "total_inflow": total_inflow,
        "total_outflow": abs(total_outflow),
        "high_risk_count": high_risk_count,
        "escalated_count": escalated_count,
    })
